package com.buildsphere.reporting.model;

public enum SectionType {
    GENERAL_POINTS,
    FACULTY_JOINED_RELIEVED,
    FACULTY_ACHIEVEMENTS,
    STUDENT_ACHIEVEMENTS,
    DEPARTMENT_ACHIEVEMENTS,
    FACULTY_EVENTS_CONDUCTED,
    STUDENT_EVENTS_CONDUCTED,
    NON_TECHNICAL_EVENTS_CONDUCTED,
    INDUSTRY_COLLEGE_VISITS,
    HACKATHON_EXTERNAL_PARTICIPATION,
    FACULTY_FDP_CERTIFICATION_ATTENDANCE,
    FACULTY_VISITS,
    PATENTS_PUBLISHED,
    VEDIC_PROGRAMS,
    PLACEMENTS,
    MOUS_SIGNED,
    SKILL_DEVELOPMENT_PROGRAMS
}
